version: '3'
services:
  loris:
    image: loris-app
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - "loris-app:/var/www/loris"
      - "loris-data:/data/loris"
      - "incoming-data:/data/incoming"
    entrypoint: docker-php-entrypoint
    command: apache2-foreground
  db:
    image: mysql:5.7
    restart: always
    env_file: .env
    volumes:
      - "mysql-data:/var/lib/mysql"
  couchdb:
    image: couchdb:2.2.0
    restart: always
    env_file: .couchdb_env
    volumes:
      - "couchdb-data:/opt/couchdb/data"
      - "couchdb-conf:/opt/couchdb/etc"
volumes:
  loris-app:
  loris-data:
  incoming-data:
  mysql-data:
  couchdb-data:
  couchdb-conf: