version: '3'
services:
  loris:
    image: loris-app
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - "loris-app:/var/www/loris"
      - "loris-data:/data/loris"
      - "incoming-data:/data/incoming"
      - "./php-ini:/usr/local/etc/php/custom.d"
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    entrypoint: docker-php-entrypoint
    command: apache2-foreground
  db:
    image: mysql:5.7
    restart: always
    env_file: .env
    volumes:
      - "mysql-data:/var/lib/mysql"
volumes:
  loris-app:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${VOLUME_PATH}/loris-app"
  loris-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${VOLUME_PATH}/loris-data"
  incoming-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${VOLUME_PATH}/incoming-data"
  mysql-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${VOLUME_PATH}/mysql-data"
